<?php

define('MIGRATE_ACCESS_BASIC', 'migration information');

/**
 * Implementation of hook_permission().
 */
function migrate_permission() {
  return array(
    MIGRATE_ACCESS_BASIC => array(
      'title' => t('Basic access to migration information'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function migrate_menu() {
  $items = array();

  $items['admin/migrate'] = array(
    'title' => 'Migrate',
    'description' => 'Monitor the creation of Drupal content from source data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_dashboard'),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
/*  $items['admin/migrate/settings'] = array(
    'title' => 'Settings',
    'description' => 'Migrate module settings',
    'weight' => 5,
    'page callback' => 'migrate_settings',
    'access arguments' => array(MIGRATE_ACCESS_ADVANCED),
    'file' => 'migrate_pages.inc',
    'type' => MENU_LOCAL_TASK,
  );*/
  $items['admin/migrate/%migration'] = array(
    'title callback' => 'migration_title',
    'title arguments' => array(2),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_migration_info', 2),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );

  if (FALSE) {
    // Not working yet
    migrate_ui_menu_add($items);
  }

  return $items;
}

// Not yet correct. Not being called by migrate_ui_menu().
// It is adding tabs to all content types, not ones with migrations.
function migrate_ui_menu_add(&$items) {
  $migrations = migrate_migrations();
  $entity_info = entity_get_info();
  foreach (array() as $key => $migration) {
    if ($info = $entity_info[$migration->destination->entityType]) {
      $bundle_info = $info['bundles'][$migration->destination->bundle];
      if (isset($bundle_info['admin'])) {
        // Extract informations from the bundle description.
        $path = $bundle_info['admin']['path'];

        $items["$path/migrate"] = array(
          'title' => strpos($path, 'comment') === FALSE ? 'Migrate' : 'Comment migrate',
          'page callback' => 'drupal_get_form',
          'page arguments' => array('migrate_migration_info', $migration->machineName),
          'access arguments' => array(MIGRATE_ACCESS_BASIC),
          'file' => 'migrate_ui/migrate_ui.pages.inc',
          'type' => MENU_LOCAL_TASK,
          'weight' => strpos($path, 'comment') === FALSE ? 2 : 18,
        );
        $items["$path/migrate/$migration->machineName"] = array(
          'title callback' => 'migration_title',
          'title arguments' => array($migration->machineName),
          'page callback' => 'drupal_get_form',
          'page arguments' => array('migrate_migration_info', $migration->machineName),
          'access arguments' => array(MIGRATE_ACCESS_BASIC),
          'type' => isset($has_default_task[$path]) ? MENU_LOCAL_TASK : MENU_DEFAULT_LOCAL_TASK,
          'file' => 'migrate_ui/migrate_ui.pages.inc',
        );
        $has_default_task[$path] = TRUE;
      }
    }
  }
}

/*
 * Implement hook_local_tasks_alter().
 *
 * Another incomplete attempt at tabs that link to migration detail pages. Help wanted.
 */
function migrate_ui_menu_local_tasks_alter($data, $router_item, $root_path) {
  // Disabled for now.
  if (FALSE) {
    dargs();
    $migrations = migrate_migrations();
    $entity_info = entity_get_info();
    foreach ($migrations as $key => $migration) {
      if ($info = $entity_info[$migration->destination->entityType]) {
        $bundle_info = $info['bundles'][$migration->destination->bundle];
        if (isset($bundle_info['admin'])) {
          // Extract informations from the bundle description.
          $path = $bundle_info['admin']['path'];
          dsm($path);
          if ($path == $router_item['tab_root']) {
            $link = array(
              'title' => 'Migrate',
              'href' => 'mw', // TODO
            );
            $data['tabs'][0]['output'][] = array(
              '#theme' => 'menu_local_task',
              '#link' => $link,
              '#active' => FALSE, // TODO
            );
            $data['tabs'][0]['count'] = $data['tabs']['count']++;
          }
        }
      }
    }
  }
}

// A menu load callback.
function migration_load($machine_name) {
  if ($machine_name) {
    $class_name = $machine_name . 'Migration';
    return Migration::getInstance($class_name);
  }
}

function migration_title($migration) {
  if (is_string($migration)) {
    $migration = migration_load($migration);
  }
  return $migration->machineName;
}
