<?php

define('MIGRATE_ACCESS_BASIC', 'migration information');

/**
 * Implementation of hook_permission().
 */
function migrate_permission() {
  return array(
    MIGRATE_ACCESS_BASIC => array(
      'title' => t('Basic access to migration information'),
    ),
/*    MIGRATE_ACCESS_ADVANCED => array(
    )*/
  );
}

/**
 * Implementation of hook_menu().
 */
function migrate_menu() {
  $items = array();

  $items['admin/content/migrate'] = array(
    'title' => 'Migrate',
    'description' => 'Monitor the creation of Drupal content from source data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_dashboard'),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  $items['admin/content/migrate/dashboard'] = array(
    'title' => 'Dashboard',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
/*  $items['admin/content/migrate/settings'] = array(
    'title' => 'Settings',
    'description' => 'Migrate module settings',
    'weight' => 5,
    'page callback' => 'migrate_settings',
    'access arguments' => array(MIGRATE_ACCESS_ADVANCED),
    'file' => 'migrate_pages.inc',
    'type' => MENU_LOCAL_TASK,
  );*/
  $items['admin/content/migrate/migration/%'] = array(
    'title' => 'Migration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_migration_info', 4),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  return $items;
}
